//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : qiyeguanli
//  @ File Name : Company.h
//  @ Date : 2017/6/26
//  @ Author : zzg
#ifndef _COMPANY_H
#define _COMPANY_H
#include <QString>

class Company {
public:
    bool IsAccess();
    QString getComMessage();
    Company(QString _name,QString _address);
private:
	QString name;
	QString address;
	QString responsor;
	QString major;
};

#endif  //_COMPANY_H
