//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : RoleOfPro.h
//  @ Date : 2017/6/26
//  @ Author : 
//
//


#if !defined(_ROLEOFPRO_H)
#define _ROLEOFPRO_H

#include "Role.h"
#include "Employee.h"
#include "Project.h"

class RoleOfPro : public Role {
public:
	Employee *1..*;
	Project *1;
};

#endif  //_ROLEOFPRO_H
