//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : RoleOfPart.h
//  @ Date : 2017/6/26
//  @ Author : 
//
//


#if !defined(_ROLEOFPART_H)
#define _ROLEOFPART_H

#include "Role.h"
#include "Apartment.h"

class RoleOfPart : public Role {
public:
	Apartment *1;
};

#endif  //_ROLEOFPART_H
