//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Role.h
//  @ Date : 2017/6/26
//  @ Author : 
//
//


#if !defined(_ROLE_H)
#define _ROLE_H

#include "Apartment.h"
#include "Employee.h"
#include "Project.h"

class Role {
public:
	void Operation1();
	Apartment *1;
	Employee *1..*;
	Project *1;
private:
	QString ID;
	QString name;
};

#endif  //_ROLE_H
